TRANSFORM:
    TRAIN_RANDOM_CROP_SIZE: (256, 256)
    TRAIN_RANDOM_ROTATE_DEG: (0, 0)
    TRAIN_HORIZONTAL_FLIP_PROB: 0.0
    TRAIN_VERTICAL_FLIP_PROB: 0.0
    TRAIN_SPECKLE_NOISE_STD: 0.0
    TRAIN_RANDOM_BRIGHTNESS_STD: 0.0
    TEST_SIZE: (928, 928)
    ALIGN_SAR_ORIENTATION: True
    TARGET_SAR_ORIENTATION: 0
DATALOADER:
    TRAIN_BATCH_SIZE: 16
    VAL_BATCH_SIZE: 16
    TEST_BATCH_SIZE: 8
    TRAIN_NUM_WORKERS: 8
    VAL_NUM_WORKERS: 8
    TEST_NUM_WORKERS: 8
    TRAIN_SHUFFLE: True
MODEL:
    ARCHITECTURE: unet
    BACKBONE: efficientnet-b7
    ENCODER_PRETRAINED_FROM: imagenet
    ACTIVATION: sigmoid
    DEVICE: cuda
    IN_CHANNELS: 4
    UNET_ENABLE_DECODER_SCSE: False
SOLVER:
    EPOCHS: 260
    OPTIMIZER: adam
    WEIGHT_DECAY: 0.0
    LR: 1e-4
    LR_SCHEDULER: multistep
    LR_MULTISTEP_MILESTONES: [230,]
    LR_MULTISTEP_GAMMA: 0.1
    LOSSES: ['dice', 'bce']
    LOSS_WEIGHTS: [1.0, 1.0]
EVAL:
    METRICS: ['iou',]
    MAIN_METRIC: 'iou/building_footprint'
